services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:2.8.0-alpine
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - caddy_logs:/var/log/caddy
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
    networks:
      - web
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80/"]
      interval: 10s
      timeout: 5s
      retries: 3

  myapi:
    build: .
    container_name: myapi
    expose:
      - "8080"
    networks:
      - web
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload

networks:
  web:
    external: true

volumes:
  caddy_data:
  caddy_config:
  caddy_logs: