services:
  caddy:
    image: caddy:2.8.0
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
    networks:
      - web
    restart: unless-stopped

  myapi:
    build: .
    container_name: myapi
    expose:
      - "8080"
    networks:
      - web
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload

networks:
  web:
    external: true

volumes:
  caddy_data:
  caddy_config: