---
- name: Test Caddy reverse proxy services
  hosts: localhost
  connection: local
  gather_facts: true
  vars_files:
    - .env
  vars:
    # Default values for local testing
    test_protocol: "https"
    test_validate_certs: no
    test_domain: "{{ DOMAIN }}"

  pre_tasks:
    - name: Detect Docker environment
      set_fact:
        in_docker: "{{ ansible_virtualization_type == 'docker' or 'docker' in ansible_fqdn }}"
      ignore_errors: yes

    - name: Set test variables for Docker environment
      when: in_docker | bool
      set_fact:
        test_protocol: "http"
        test_domain: "localhost"
        test_validate_certs: no

    - name: Display test configuration
      debug:
        msg: |
          Test Configuration:
          - Protocol: {{ test_protocol }}
          - Domain: {{ test_domain }}
          - Validate Certs: {{ test_validate_certs }}

  tasks:
    - name: Include test cases for each subdomain
      include_tasks: test_services.yml
      loop:
        - { name: "api", port: 80, path: "/" }
        - { name: "web", port: 80, path: "/" }
        - { name: "auth", port: 80, path: "/" }
      loop_control:
        loop_var: service

    - name: Test HTTPS redirect
      uri:
        url: "http://{{ DOMAIN }}"
        method: GET
        follow_redirects: none
        status_code: 301, 302
        timeout: 10
      register: http_redirect
      failed_when: false

    - name: Verify HTTPS redirect
      assert:
        that:
          - "'https://' in http_redirect.redirected_url"
          - "http_redirect.redirected_url == 'https://' ~ DOMAIN ~ '/'"
        fail_msg: "HTTPS redirect failed"

    - name: Test HTTP/2 support
      uri:
        url: "https://{{ DOMAIN }}"
        method: GET
        validate_certs: no
        timeout: 10
      register: http2_test
      failed_when: false

    - name: Verify HTTP/2 support
      assert:
        that:
          - "http2_test.status == 200"
          - "'HTTP/2' in http2_test.msg"
        fail_msg: "HTTP/2 not supported"
